### ISSUE TITLE
Unable to generate coco images

### ISSUE THREAD

**Issue by Vgandhi9** [mansimov/text2image#13]
I am unable to generate images for the MS COCO example. Once the weights are saved I run the command 

`python sample-captions.py --model models/coco-captions-32x32.json --weights ./attention-vae-2016-6-29-5-2-31.h5  --dictionary ../dictionary.pkl --gan_path ../gan.hdf5 --skipthought_path /home/skip-thoughts`

But in the coco-captions-32X32.json file, there is no key "costFunction". 
The exact error that I am getting is as follows

Traceback (most recent call last):
  File "sample-captions.py", line 79, in <module>
    costFunctionType = str(model["model"][0]["costFunction"]["type"])
KeyError: 'costFunction'

Can you please share the updated coco-captions-32X32.json file?

Thanks.

**Comment by ryanfb** [comment]
Looking through `sample-captions.py` and the rest of the code, I couldn't find where these variables assigned from the `costFunction` key were actually used anywhere else: https://github.com/emansim/text2image/blob/master/coco/sample-captions.py#L79-L80

Simply commenting them out let `sample-captions.py` run to completion.
